### ISSUE TITLE
EmptyRecycle calls undefined method from OC dav app

### ISSUE THREAD

**Issue by mirekys** [pondersource/oc-sciencemesh#23]
Running on `bitnami/owncloud:latest` docker image, but with: https://github.com/pondersource/core (reva-sharees branch) used for owncloud core sources, calling EmptyRecycle API fails with:

```json
{
  "reqId": "pae6ytFPQ6ZIfL74tPuj",
  "level": 3,
  "time": "2022-10-07T09:47:20+00:00",
  "remoteAddr": "10.10.231.204",
  "user": "--",
  "app": "index",
  "method": "POST",
  "url": "/index.php/apps/sciencemesh/~test/api/storage/EmptyRecycle",
  "message": {
    "Exception": "Error",
    "Message": "Call to undefined method OCA\\DAV\\TrashBin\\TrashBinManager::listTrashRoot()",
    "Code": 0,
    "Trace": [
      "#0 /opt/bitnami/owncloud/lib/private/AppFramework/Http/Dispatcher.php(170): OCA\\ScienceMesh\\Controller\\RevaController->EmptyRecycle()",
      "#1 /opt/bitnami/owncloud/lib/private/AppFramework/Http/Dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController()",
      "#2 /opt/bitnami/owncloud/lib/private/AppFramework/App.php(100): OC\\AppFramework\\Http\\Dispatcher->dispatch()",
      "#3 /opt/bitnami/owncloud/lib/private/AppFramework/Routing/RouteActionHandler.php(47): OC\\AppFramework\\App::main()",
      "#4 /opt/bitnami/owncloud/lib/private/Route/Router.php(344): OC\\AppFramework\\Routing\\RouteActionHandler->__invoke()",
      "#5 /opt/bitnami/owncloud/lib/base.php(928): OC\\Route\\Router->match()",
      "#6 /opt/bitnami/owncloud/index.php(54): OC::handleRequest()",
      "#7 {main}"]
    "File": "/opt/bitnami/owncloud/apps/sciencemesh/lib/Controller/RevaController.php",
    "Line": 462
  }
}
```

There seems to be no such function like `listTrashRoot ` in the recent implementations of [TrashBinManager](https://github.com/owncloud/core/blob/v10.10.0/apps/dav/lib/TrashBin/TrashBinManager.php)

**Comment by michielbdejong** [comment]
Fixed, see my comments on https://github.com/sciencemesh/oc-sciencemesh/issues/4
